include (":app")
rootProject.name = "NoteApp"
include(":features:home:domain")
include(":features:home:data")
include(":core:datasource:local")
include(":features:home:ui")
include(":features:note_details:domain")
include(":core:di")
include(":features:note_details:data")
include(":core:ui")
include(":core:domain")
